repos:
    -   repo: https://github.com/psf/black
        rev: 22.1.0
        hooks:
        -   id: black
            name: Format Python Code (black) in Fw/Python/
            files: '^Fw/Python/'
        -   id: black
            name: Format Python Code (black) in Gds/
            files: '^Gds/'
            exclude: '^Gds/src/fprime_gds/wxgui/'